### ISSUE TITLE
Error on processing some samples

### ISSUE THREAD

**Issue by aheravi** [icbi-lab/quanTIseq#10]
Hello,
I am running quanTIseq on some of my rna-seq libraries and most of them finished successfully. In one case, I am getting errors and it seems like the TrimmomaticPE fails to process the fastqs. I ran TrimmomaticPE outside the container with no error.
Is there anything else I can check?

Thanks,
Ali

**Comment by chripla** [comment]
Hi Ali,

I am sorry to hear about your problems. Can you please send us the error messages you get and also the input commands you are using for quanTIseq and for TrimmomaticPE? 

Thanks,
Christina

**Comment by aheravi** [comment]
Hi Christina,
Thanks for your prompt reply.
Here are the error message and my TrimmomaticPE command:
```
Exception in thread "main" java.io.FileNotFoundException: /opt/quantiseq/Input/C3_6_1_None_100bp.concat_chastity_passed.fastq.gz (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:135)
        at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:264)
        at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:539)
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
```

```
java -jar trimmomatic-0.39.jar PE -threads 20 -phred33 /fastq//C3_6_1_None_100bp.concat_chastity_passed.fastq.gz /fastq//C3_6_2_None_100bp.concat_chastity_passed.fastq.gz C3_6_1_None_100bp.concat_chastity_passed.fastq.gz C3_6_1_None_100bp.concat_chastity_passed.fastq.gz_nopair C3_6_2_None_100bp.concat_chastity_passed.fastq.gz C3_6_2_None_100bp.concat_chastity_passed.fastq.gz_nopair LEADING:20 TRAILING:20 MINLEN:36 CROP:1000
```

**Comment by chripla** [comment]
Hi Ali, 
seems like the input file cannot be reached by the pipeline. Could you also send me the command you are using for running quanTIseq and the input file? Thanks!
Christina

**Comment by chripla** [comment]
I will close this issue now, but feel free to reopen or add a new issue if there are any problems. 
Cheers,
Christina
